# .travis.yml
language: ruby
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.27.4
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - make pull_image
  - make build_image

script:
  - make test_app

branches:
  only:
    - master
