version: '3.7'
services:
  app1:
    container_name: app1
    shm_size: '1000000000'
    image: centos-flask:0.1
    environment:
        WORK_DIR: 'app/sample-flask'
    tty: true
    expose:
      - 8080
    ports:
      - '8080:8080'
    volumes:
      - './app/sample-flask:/home/user'
      - '/usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro'
    command: >
      bash -c "gunicorn -c gunicorn_config.py 'run:create_app()'"


  nginx:
    container_name: nginx80
    image:
      nginx:stable
    tty: true
    expose:
      - 80
    links:
      - app1
    ports:
      - '80:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '/usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro'
    command: >
      bash -c "nginx -g 'daemon off;'"
    mem_limit: 2G
    mem_reservation: 1G
    cpus: '.5'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: always